create table category (id bigint generated by default as identity (start with 1), status varchar(255), name varchar(255), primary key (id))
create table composer (id bigint generated by default as identity (start with 1), status varchar(255), name varchar(255), primary key (id))
create table singer (id bigint generated by default as identity (start with 1), status varchar(255), name varchar(255), primary key (id))
create table song (id bigint generated by default as identity (start with 1), status varchar(255), description varchar(255), lyrics varchar(255), singlish_name varchar(255), sinhala_name varchar(255), category_id bigint, composer_id bigint, singer_id bigint, writer_id bigint, primary key (id))
create table writer (id bigint generated by default as identity (start with 1), status varchar(255), name varchar(255), primary key (id))
alter table song add constraint FKsxgtyi08dc9tqp0iyva3ih0kn foreign key (category_id) references category
alter table song add constraint FK8jk18obe0eyrb2i9wptl2jufs foreign key (composer_id) references composer
alter table song add constraint FKnt7ra6v3hsvahew2b735i31wf foreign key (singer_id) references singer
alter table song add constraint FKa5oukmbgp5xptjf1qnuogk13l foreign key (writer_id) references writer
